name: ğŸ§‘â€ğŸ’» Lint

on:
  workflow_call:
jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: â˜ï¸ Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: ğŸ”§ Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: ğŸ”§ Install npm@latest
        run: npm i -g npm@latest

      - name: ğŸ“¦ Install dependencies
        uses: bahmutov/npm-install@v1

      - name: ğŸ” Lint Code Base
        run: npm run lint --if-present
      # uses: github/super-linter/slim@v4
      # env:
      #   VALIDATE_ALL_CODEBASE: true
      #   VALIDATE_${{inputs.LINTER_OPTION}}: true
      #   VALIDATE_HTML: true
      #   IGNORE_GITIGNORED_FILES: true
      #   LINTER_RULES_PATH: .
      #   TYPESCRIPT_ES_CONFIG_FILE: .eslintrc.cjs
      #   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
